version: '2'

services:
  nginx:
    build: docker/nginx
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./:/app

  php:
    image: php:7.0-fpm
    volumes:
      - ./:/app
    working_dir: /app
